### ISSUE TITLE
shutdown method for AsyncWriteExt

### ISSUE THREAD

**Issue by v1gnesh** [smol-rs/async-compat#24]
When using the [async-compression](https://docs.rs/async-compression/latest/async_compression/index.html) crate, I'm able to sprinkle `.compat()` or `Compat::new(...)` generously to silence most errors.
However, `encoder.shutdown` needs `poll_shutdown`, and I see that's not available in smol::io::AsyncWriteExt.

Is there any chance of adding `poll_shutdown()` and `shutdown()`, so that the smol runtime works with async-compression?

Thanks in advance for sharing your work (in general), and for writing about it!

**Comment by taiki-e** [comment]
poll_close/close is the equivalent of poll_shutdown/shutdown.
