### ISSUE TITLE
CompatExt is implemented for any T

### ISSUE THREAD

**Issue by Miha-Rozina** [smol-rs/async-compat#25]
Since `CompatExt` is implemented for any T, this means that IDEs give you suggestions for its functions on every object, which for most objects is just spam. Is it possible to implement `CompatExt` only for types that implement the `Future` trait? Since `Compat` is a future only when its inner type is a `Future`, it would make sense that `CompatExt` is only implemented for types that implement `Future` trait.

**Comment by notgull** [comment]
`Compat` also has implementations for other traits, like `tokio::AsyncRead`. So this wouldn't work.

**Comment by Miha-Rozina** [comment]
Ah right, didn't notice that. Well that sucks, but I guess not much can be done in current version of Rust.
